name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev zlib1g-dev build-essential libssl-dev libffi-dev openjdk-17-jdk ant autoconf automake libtool patch
          pip install --upgrade pip
          pip install buildozer cython kivy cryptography requests

      - name: Accept Android Licenses (Force)
        run: |
          # Cette commande crée les fichiers de licence acceptés avant le lancement de Buildozer
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          # On accepte toutes les licences possibles pour le SDK manager
          yes | sdkmanager --licenses || true
          
      - name: Build APK
        run: |
          # On définit une variable pour éviter que Buildozer cherche des versions trop récentes (37)
          export APP_ANDROID_BUILD_TOOLS_VERSION="33.0.0"
          # On utilise "yes" pour valider les licences spécifiques à Buildozer
          yes | buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CashControl-Final-APK
          path: bin/*.apk
