name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # Mise à jour v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Mise à jour v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev zlib1g-dev build-essential libssl-dev libffi-dev openjdk-17-jdk
          pip install buildozer cython kivy cryptography requests

      - name: Build APK
        run: |
          yes | buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4 # LA CORRECTION EST ICI
        with:
          name: CashControl-Final-APK
          path: bin/*.apk
